AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-startstop

  Sample SAM Template for sam-startstop

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 60
    MemorySize: 128

Resources:
  StartEnvironment:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: StartEnvironment
      CodeUri: start_ec2
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Role: arn:aws:iam::902550277123:role/StartStopRole
      Events:
       EvenBridgeSchedule:
        Type: ScheduleV2
        Properties:
          Name: Startenvironment
          Description: Start environment on the days that I work
          ScheduleExpression: cron(30 6 ? * 2,5,6 *)
          State: ENABLED

  StopEnvironment:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      FunctionName: StopEnvironment
      CodeUri: stop_ec2
      Handler: lambda_function.lambda_handler
      Runtime: python3.10
      Architectures:
        - x86_64
      Role: arn:aws:iam::902550277123:role/StartStopRole
      Events:
       EvenBridgeSchedule:
        Type: ScheduleV2
        Properties:
          Name: StopEnvironment
          Description: Start environment on the days that I work
          ScheduleExpression: cron(* 16 ? * 2,5,6 *)
          State: ENABLED

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM 
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  
  StopEnvironment:
    Description: "StopEnvironment Lambda Function ARN"
    Value: !GetAtt StopEnvironment.Arn
  StartEnvironment:
    Description: "StartEnvironment Lambda Function ARN"
    Value: !GetAtt StartEnvironment.Arn

